paths:

  /api/products/:
    get:
      summary: Retorna lista de productos
      tags:
      - Products
      responses:
        '200':    # status code
          description: Obtensión correcta de productos desde db
        '500':
          description: Error interno del servidor
    post: 
      summary: Crea un nuevo producto
      tags: 
      - 
      Products
      responses:
        '201':
          description: Producto creado correctamente
        '500':
          description: Error interno del servidor
    put:
      summary: Actualiza un usuario existente en DB
      tags: 
      - Products
      responses:
        '201':
          description: Producto modificado correctamente
        '500':
          description: Error interno del servidor
    delete:
        summary: Elimina un producto de la DB
      tags: 
      - Products
      responses:
        '201':
          description: Producto eliminado correctamente
        '500':
          description: Error interno del servidor

components:
  schemas:
    Products:
      type: Object
      properties:
        _id:
          type: ObjectId
          description: id autogenerado por Mongo
        price:
          type: Number
          description: Precio del producto
        description:
          type: String
          description: Descripción del producto
        title:
          type: String
          description: Titulo del producto
        stock:
          type: Number
          description: Stock del producto
        thumbnail:
          type: String
          description: Imagen del producto
        status:
          type: Boolean
          description: Estado del producto
        code:
          type: String
          description: Código del producto
